const EX = {
  g1_cp:  {id:"g1_cp",  name:"Chest Press Machine",    scheme:"4×5+",   sets:4,reps:5,  repType:"plus",  hasWeight:true,  rmMult:0.85*0.80,
            alts:["Dumbbell Bench Press","Smith Machine Bench","Cable Chest Press"], gifUrl:""},
  g1_spm: {id:"g1_spm", name:"Shoulder Press Machine", scheme:"3x10",   sets:3,reps:10,  repType:"fixed",  hasWeight:true,  rmMult:0.85*0.60,
            alts:["Dumbbell OHP","Arnold Press","Machine Lateral Raise"], gifUrl:""},
  g1_rdl: {id:"g1_rdl", name:"Romanian DL",            scheme:"3x8",   sets:3,reps:8,  repType:"fixed",  hasWeight:true,  rmMult:0.85*0.60,
            alts:["Stiff-Leg Deadlift","Cable Pull-Through","DB Romanian DL"], gifUrl:""},
  g1_lpd: {id:"g1_lpd", name:"Lat Pulldown",           scheme:"3x10-14",   sets:3,reps:10,  repType:"range",  hasWeight:true,  rmMult:0.85*0.65,
            alts:["Cable Wide-Grip Pulldown","Assisted Pull-Up","Straight-Arm Pulldown"], gifUrl:""},
  g1_le:  {id:"g1_le",  name:"Leg Extension",          scheme:"3x10-14",   sets:3,reps:10,  repType:"range",  hasWeight:true,  rmMult:0.85*0.65,
            alts:["Terminal Knee Extension","Sissy Squat","Step-Up with Knee Drive"], gifUrl:""},
  g1_cr:  {id:"g1_cr",  name:"Crunch",                 scheme:"3×max",  sets:3,reps:0,  repType:"max",   hasWeight:false, rmMult:0,
            alts:["Ab Wheel","Cable Crunch","Decline Crunch"], gifUrl:""},

  g2_lp:  {id:"g2_lp",  name:"Leg Press",              scheme:"4×5+",   sets:4,reps:5, repType:"plus", hasWeight:true,  rmMult:0.85*0.70,
            alts:["Hack Squat","Smith Machine Squat","Goblet Squat"], gifUrl:""},
  g2_cp:  {id:"g2_cp",  name:"Chest Press Machine",    scheme:"3×10",   sets:3,reps:10, repType:"fixed", hasWeight:true,  rmMult:0.85*0.60,
            alts:["Dumbbell Bench Press","Smith Machine Bench","Cable Chest Press"], gifUrl:""},
  g2_pu:  {id:"g2_pu",  name:"Pull Ups",               scheme:"3×max",  sets:3,reps:0,  repType:"max",   hasWeight:false, rmMult:0,
            alts:["Lat Pulldown","Assisted Pull-Up","Cable Straight-Arm Pushdown"], gifUrl:""},
  g2_lr:  {id:"g2_lr",  name:"Lateral Raises",         scheme:"3×10-14",sets:3,reps:10, repType:"range", hasWeight:true,  rmMult:0.85*0.60,
            alts:["Cable Lateral Raise","Upright Row","Machine Lateral Raise"], gifUrl:""},
  g2_idc: {id:"g2_idc", name:"Incline Dumbbell Curl",  scheme:"3×8-12", sets:3,reps:8,  repType:"range", hasWeight:true,  rmMult:0.85*0.75,
            alts:["Barbell Curl","Hammer Curl","Cable Curl"], gifUrl:""},
  g2_lgr: {id:"g2_lgr", name:"Leg Raises",             scheme:"3×max",  sets:3,reps:0,  repType:"max",   hasWeight:false, rmMult:0,
            alts:["Hanging Knee Raise","Reverse Crunch","Flutter Kicks"], gifUrl:""},

  g3_sp:  {id:"g3_sp",  name:"Smith Machine Shoulder", scheme:"4×5+",   sets:4,reps:5,  repType:"plus",  hasWeight:true,  rmMult:0.85*0.70,
            alts:["Dumbbell OHP","Arnold Press","Landmine Press"], gifUrl:""},
  g3_lp:  {id:"g3_lp",  name:"Leg Press",              scheme:"3×10",   sets:3,reps:10, repType:"fixed", hasWeight:true,  rmMult:0.85*0.60,
            alts:["Hack Squat","Smith Machine Squat","Goblet Squat"], gifUrl:""},
  g3_br:  {id:"g3_br",  name:"Barbell Row",            scheme:"4×10",   sets:4,reps:10, repType:"fixed", hasWeight:true,  rmMult:0.85*0.60,
            alts:["Dumbbell Row","Cable Seated Row","T-Bar Row"], gifUrl:""},
  g3_cf:  {id:"g3_cf",  name:"Chest Fly Machine",      scheme:"3×10-14",sets:3,reps:10, repType:"range", hasWeight:true,  rmMult:0.85*0.65,
            alts:["Cable Fly","Dumbbell Fly","Pec Deck"], gifUrl:""},
  g3_cpd: {id:"g3_cpd", name:"Cable Pushdown",         scheme:"3×8-12", sets:3,reps:8,  repType:"range", hasWeight:true,  rmMult:0.85*0.75,
            alts:["Overhead Triceps Extension","Dumbbell Kickback","Bench Dips"], gifUrl:""},
  g3_pl:  {id:"g3_pl",  name:"Plank",                  scheme:"3×max",  sets:3,reps:0,  repType:"max",   hasWeight:false, rmMult:0,
            alts:["RKC Plank","Dead Bug","Pallof Press"], gifUrl:""},
};

const DAYS = [
  ["g1_cp","g1_spm","g1_rdl","g1_lpd","g1_le","g1_cr"],
  ["g2_lp","g2_cp","g2_pu","g2_lr","g2_idc","g2_lgr"],
  ["g3_sp","g3_lp","g3_br","g3_cf","g3_cpd","g3_pl"],
];

function getDayExs(d){ return DAYS[d % 3].map(id => EX[id]); }
const WEIGHT_EX_IDS = Object.values(EX).filter(e=>e.hasWeight).map(e=>e.id);

const EXERCISE_GIFS = {
  "Chest Press Machine": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Chest-Press-Machine.gif",
  "Dumbbell Bench Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Press-1.gif",
  "Smith Machine Bench": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Smith-Machine-Bench-Press.gif",
  "Cable Chest Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Seated-Cable-Chest-Press.gif",
  "Shoulder Press Machine": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Lever-Shoulder-Press.gif",
  "Dumbbell OHP": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Standing-Dumbbell-Overhead-Press.gif",
  "Arnold Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Arnold-Press.gif",
  "Machine Lateral Raise": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Lateral-Raise-Machine.gif",
  "Romanian DL": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Barbell-Romanian-Deadlift.gif",
  "Stiff-Leg Deadlift": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Stiff-Leg-Deadlift.gif",
  "Cable Pull-Through": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Cable-Pull-Through.gif",
  "DB Romanian DL": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Romanian-Deadlift.gif",
  "Lat Pulldown": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Lat-Pulldown.gif",
  "Cable Wide-Grip Pulldown": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Lat-Pulldown.gif",
  "Assisted Pull-Up": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Assisted-Pull-up.gif",
  "Straight-Arm Pulldown": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Cable-Straight-Arm-Pulldown.gif",
  "Leg Extension": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/LEG-EXTENSION.gif",
  "Terminal Knee Extension": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Terminal-Knee-Extension.gif",
  "Sissy Squat": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/sissy-squat.gif",
  "Step-Up with Knee Drive": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Step-up.gif",
  "Crunch": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Crunch.gif",
  "Ab Wheel": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Ab-Wheel-Rollout.gif",
  "Cable Crunch": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Standing-Cable-Crunch.gif",
  "Decline Crunch": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Decline-Sit-up.gif",
  "Leg Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Leg-Press.gif",
  "Hack Squat": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Sled-Hack-Squat.gif",
  "Smith Machine Squat": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/smith-machine-squat.gif",
  "Goblet Squat": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Heel-Elevated-Goblet-Squat.gif",
  "Pull Ups": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pull-up.gif",
  "Cable Straight-Arm Pushdown": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pushdown.gif",
  "Lateral Raises": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Lateral-Raise.gif",
  "Cable Lateral Raise": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Cable-Lateral-Raise.gif",
  "Upright Row": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Barbell-Upright-Row.gif",
  "Incline Dumbbell Curl": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Flexor-Incline-Dumbbell-Curls.gif",
  "Barbell Curl": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Barbell-Curl.gif",
  "Hammer Curl": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Hammer-Curl.gif",
  "Cable Curl": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/cable-curl.gif",
  "Leg Raises": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Lying-Leg-Raise.gif",
  "Hanging Knee Raise": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Hanging-Knee-Raise.gif",
  "Reverse Crunch": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Reverse-Crunch-1.gif",
  "Flutter Kicks": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Flutter-Kicks.gif",
  "Smith Machine Shoulder": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Smith-Machine-Shoulder-Press.gif",
  "Landmine Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Kneeling-Landmine-Press.gif",
  "Barbell Row": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Barbell-Bent-Over-Row.gif",
  "Dumbbell Row": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Row.gif",
  "Cable Seated Row": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Seated-Cable-Row.gif",
  "T-Bar Row": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/t-bar-rows.gif",
  "Chest Fly Machine": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pec-Deck-Fly.gif",
  "Cable Fly": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Cable-Crossover.gif",
  "Dumbbell Fly": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Fly.gif",
  "Pec Deck": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pec-Deck-Fly.gif",
  "Cable Pushdown": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pushdown.gif",
  "Overhead Triceps Extension": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Seated-One-Arm-Dumbbell-Triceps-Extension.gif",
  "Dumbbell Kickback": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dumbbell-Kickback.gif",
  "Bench Dips": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Bench-Dips.gif",
  "Plank": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/plank.gif",
  "RKC Plank": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/RKC-Plank.png",
  "Dead Bug": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Dead-Bug.gif",
  "Pallof Press": "https://raw.githubusercontent.com/furkankkokcek/fitness/main/exercises/Pallof-Press.gif"
};

